### ISSUE TITLE
MOGA Pocket Support?

### ISSUE THREAD

**Issue by mekanisk** [Zel-os/MogaSerial#4]
I unfortunately don't have a MOGA Power Pro, and I'm stuck with a little Pocket model. From what I understand, Pocket works differently from its counterpart, and it's certainly showing. When I try connecting to MogaSerial, it works for about a second, then disconnects and tries again. This loop continues seemingly endlessly, and I'm never actually able to control anything with the device. The Pocket works flawlessly on my Android with the MOGA Universal Driver app by Ryan Loebs, available on the Google Play Store. Any help would be greatly appreciated.

Also, my controller appears as "BD&A" in the Bluetooth list, not MOGA Pocket or anything like that.

**Comment by Zel-os** [comment]
Unfortunately I wasn't able to get ahold of an old Moga Pocket to test with, but I _believe_ it should work in vJoy mode with the triggers set to "button".  MogaSerial will use different communication codes with those settings that I'm pretty sure were meant for the older Pocket model.

**Comment by oryonatan** [comment]
Update after restart it works.

Doesn't seem to work 
(Windows 10)

**Comment by tuppaacc** [comment]
Sadly I can also attest that this does not work on surface pro 4 windows 10, all it does it cycles through connect -> disconnect -> connect -> disconnect... endlessly on Vjoy or xbox setting.

There is another program that has it working called "zeemouse" unfortunately my computer reads it as a virus so I had to delete it not before testing it and it does work. in a way not exactly the same as your program. (http://www.bitbanksoftware.com/tinytools.html)

If I send you a test unit can you add support for it? they are like $13 on Amazon, really cheap and convenient for the casual gamer.

**Comment by SchNiVas** [comment]
I have same issue exactly as described by tuppaacc. zeemouse works, but won't do keyboard binding properly. Every time I go into and set, it resets.
But as for MogaSerial. I've gotten everything to work all the way to the connect and disconnect issue. I too have a Surface Pro 4 Win 10 x64, though I don't believe the Surface Pro fact is related... Said that this doesn't work....
I have the Moga Pocket.

**Comment by Zel-os** [comment]
The Moga Pocket is not officially supported, but with the following settings it will work:

- Set input driver to `vJoy`
- Set trigger mode to `Button`

Duplicated by issue https://github.com/Zel-os/MogaSerial/issues/7
