### ISSUE TITLE
Network Adapter issues during MogaSerial connect.

### ISSUE THREAD

**Issue by Slyther** [Zel-os/MogaSerial#5]
Issue being experienced on a Dell Inspiron 5421 Laptop featuring an Intel® Centrino® Wireless-N 2230 Wireless & Bluetooth card, which is the piece of hardware in specific that's experiencing this issue.

While MogaSerial tries to connect to the controller, the Network Adapter will stop operating until MogaSerial either connects to the controller or fails, in which case it will display the message "Reconnecting in 3 seconds..." and all network operations will resume. If it never connects to the controller, the Network Adapter will seem to be having network intermittence issues, since it stops sending and receiving any sort of information during this time, but resumes as soon as MogaSerial either connects to the controller, fails and pauses, or gets stopped.

In the following video I demonstrate this issue by using iperf to run a network bandwidth test alongside another computer on my network:

https://youtu.be/7jrqL7o70PE

The first time the test is carried out, no issues happen, but as soon as MogaSerial begins looking for the device, the test is brought to a halt until connection is eventually dropped by the peer computer.

This could very well be how Bluetooth actually behaves, or how my adapter behaves, but it might also be a bug on your side, in which case it's too disruptive of an issue for me to not let you know about it.

**Comment by Zel-os** [comment]
Unfortunately, from everything I've been able to tell this is a common problem with integrated wireless & Bluetooth adapters, and the best I can do is refer you to the [Microsoft knowledgebase article about the issue](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/wifi-limiteddisconnected-when-bluetooth-is-enabled/8871aae8-d975-4906-88b7-a62ce3127df4).

Bluetooth adapters put out a lot of noise during the connection process, and if the channel it picks happens to overlap with the one wi-fi is using, they appear to cause a lot of interference with each other.  It seems to vary wildly between devices and driver versions as well.  The downside is that there's nothing I've found that can be done within the code of MogaSerial to compensate.

Duplicated by issue https://github.com/Zel-os/MogaSerial/issues/8
