### ISSUE TITLE
Driver does not connect to MOGA Pocket. 

### ISSUE THREAD

**Issue by lgstoian** [Zel-os/MogaSerial#7]
I put the Moga Pocket in sync mode ( blue light flashing ). It is already paired with the pc so I click connect in the app. It instantly connects , the light on the controller becomes green to signal a successful connection. About two seconds later it disconnects and tries to connect again over and over again.

**Comment by SchNiVas** [comment]
Same Issue. Moga Pocket Doesn't work. Issue Confirmed. All expected Drivers installed as requested. Running Windows 10 x64. Connects then immediately disconnects.

**Comment by Zel-os** [comment]
The Moga Pocket is not officially supported, but with the following settings it may work:

- Set input driver to `vJoy`
- Set trigger mode to `Button`

This will use older control codes that I *think* will work, but as of yet nobody has given a clear report of success or failure.

Duplicated by issue https://github.com/Zel-os/MogaSerial/issues/4

**Comment by joonatoona** [comment]
vJoy has the same issue.

**Comment by SchNiVas** [comment]
I have confirmed that what Zel-os suggested worked perfectly with the MOGA Pocket!!!
